### ISSUE TITLE
engine: implement engine

### ISSUE THREAD

**Issue by tsatke** [tomarrell/lbadd#177]
Implement an engine that can execute our IR.

Scope:
- [ ] define file format (#178)
- [ ] implement support for file format (#180)
- [x] add high level profiling (#181)
- [x] add integration tests (#182)
- [ ] add benchmarks (#183)
- [ ] add documentation documents
